### ISSUE TITLE
Files duplicated: function.php

### ISSUE THREAD

**Issue by merolhack** [drahulsingh/Medstore-Management-System#2]
What's the difference between these two files?:

- assets\function.php
- include\function.php

They has the exact functions...

**Comment by drahulsingh** [comment]
The difference between the two files lies primarily in their directory paths:

1. assets\function.php: This file is located in the "assets" directory. Typically, the "assets" directory is used for storing resources like images, CSS, JavaScript files, and sometimes PHP files that are part of the front-end assets.

2. include\function.php: This file is located in the "include" directory. The "include" directory is generally used for storing PHP files that are meant to be included in other PHP scripts. These files often contain reusable code, such as functions, classes, or configuration settings.

Even though both files contain the exact same functions, their directory placement suggests different intended uses or organizational strategies within your project. It might be a good idea to consolidate these files into one location to avoid redundancy and potential confusion.
